/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import { GoogleGenAI, Type } from "@google/genai";
import { AnalysisResult, GeneratedImage, RawLoreEntry, FormattedLoreResult } from "../types";

export const generateInfographic = async (query: string): Promise<GeneratedImage> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const prompt = `
Create an explanation-driven, sparse-text, rich image about: "${query}"

IMPORTANT STYLE GUIDELINES:
- Create a diagram or infographic but with minimal text - keep it visually focused
- Focus on compelling imagery, scenes, objects, or artistic representations
- Use dramatic lighting, rich colors, and cinematic composition
- Think editorial photography or concept art, not charts or diagrams
- The image should be atmospheric and immersive

Generate a stunning visual that captures the essence of the topic through imagery, not words.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: prompt,
      config: {
        imageConfig: {
          aspectRatio: '16:9',
        },
      },
    });

    // Extract Image
    let imageBase64: string | undefined;
    let mimeType = 'image/png';

    // The response structure for images in gemini-2.5-flash-image contains multiple parts
    const parts = response.candidates?.[0]?.content?.parts;
    
    if (parts) {
      for (const part of parts) {
        if (part.inlineData) {
            imageBase64 = part.inlineData.data;
            mimeType = part.inlineData.mimeType || 'image/png';
            break;
        }
      }
    }

    if (!imageBase64) {
      throw new Error("No image generated by the model.");
    }

    // Extract Grounding Metadata (Likely empty for flash-image without tools, but kept for safety)
    const groundingUrls: Array<{ title: string; uri: string }> = [];
    // flash-image doesn't support tools currently in this config, so this will likely be empty
    const chunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks;
    if (chunks) {
        chunks.forEach(chunk => {
            if (chunk.web) {
                groundingUrls.push({ title: chunk.web.title || 'Source', uri: chunk.web.uri || '#' });
            }
        });
    }

    return {
      base64: imageBase64,
      mimeType,
      groundingUrls
    };

  } catch (error) {
    console.error("Image Generation Error:", error);
    throw error;
  }
};

export const analyzeImageRegions = async (query: string, imageBase64: string): Promise<AnalysisResult> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const prompt = `
Analyze this image about "${query}" and identify interesting regions to annotate.
Use Google Search to verify facts, statistics, and find reputable source URLs.

Identify 4-6 distinct visual areas in the image. For each area, provide widget data.

CRITICAL CONTENT GUIDELINES:
- **RICH DESCRIPTIONS:** Do not write one-liners. Descriptions must be 2-3 sentences, immersive, and educational. Explain *why* this part matters.
- **ICONS:** "icon" must be a SINGLE valid Emoji that visually represents the segment. Do not leave blank.
- **TONE:** Scientific, futuristic, yet accessible. 

For each segment, choose the BEST format from:
- "compact": Standard card (use for most items).
- "stats": Focus on numerical data points (use if you can invent or cite plausible metrics).
- "detailed": Long-form explanation for the central subject.

Provide this data:
- "label": Name (1-4 words)
- "format": "compact" | "stats" | "detailed"
- "description": Rich text (approx 30-50 words).
- "category": "concept" | "data" | "process" | "structure"
- "icon": A single relevant emoji (e.g. 🧬, ⚡, 🌌).
- "stats": Array of facts (ONLY for stats/detailed formats) { "label", "value" }
- "sourceUrl": A relevant Wikipedia or educational URL found via search.
- "sourceName": Short name for the source.
- "bounds": { "x": number (0-100), "y": number (0-100), "width": number (0-100), "height": number (0-100) }

Mix formats. Ensure the "bounds" accurately target specific visual elements in the image.

Return as JSON:
{
  "segments": [ ... ]
}

Return ONLY valid JSON.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash', 
      contents: [
        {
          role: 'user',
          parts: [
            { text: prompt },
            {
              inlineData: {
                mimeType: 'image/png',
                data: imageBase64,
              },
            },
          ],
        },
      ],
      config: {
          tools: [{ googleSearch: {} }]
      }
    });

    const text = response.text;
    if (!text) throw new Error("No analysis generated");

    // Basic cleanup just in case JSON mode misses something or adds markdown
    const cleanText = text.replace(/```json/g, '').replace(/```/g, '').trim();
    return JSON.parse(cleanText) as AnalysisResult;

  } catch (error) {
    console.error("Image Analysis Error:", error);
    throw error;
  }
};

export const formatLoreEntry = async (
  entry: RawLoreEntry,
  decoder: 'forge' | 'chronicle' | 'echelon'
): Promise<FormattedLoreResult> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  let styleGuide = '';
  if (decoder === 'forge') {
    styleGuide = `
Format this text like a heavy industrial mechanics log of Abyssum. Use rustic, heat-treated, heavy metal, steam-driven terminology.
Tone: Steampunk, molten energy, and industrial guild rebellion. Highlight mechanical joints, scrap parts, thermal heat-pipes, and resonance.`;
  } else if (decoder === 'chronicle') {
    styleGuide = `
Format this text like a rogue gothic investigative occult case-file of the Shibuya District. Use detective noir, rain-slick streets, paranormal anomaly, and bio-cybernetic terminology.
Tone: Gothic cyberpunk horror, secretive whistleblowers, print-press undercurrents, and yellow neon-gas lanterns. Highlight bio-negatives, shadow tendrils, and mental burns.`;
  } else {
    styleGuide = `
Format this text like a high-altitude cyber-shrine architectural scroll of Echelon. Use royal corporate knight, sky-tournament, and cybermatic divine terminology.
Tone: Royal sci-fi, elite high-tech chivalry, plasma banners, titanium shields, hover-beast mounts, and high-altitude gravity fluctuations. Highlight sky-cores, aether fields, and gravity locks.`;
  }

  const prompt = `
You are the Genesis Verse Decryption Engine.
You must analyze and format this encrypted raw transmission text:

"${entry.rawText}"

Metadata Context:
Identifier: ${entry.id}
Original Title: ${entry.title}
Source Sector: ${entry.source}
Anomalous Category: ${entry.category}
Target Hero Gateway: ${entry.targetCharacter}
Classified Clearance: ${entry.secureLevel}
Acquisition Cycle: ${entry.date}

DECRYPTION FILTER / TRANS-CODER PATTERN ACTIVATED: [${decoder.toUpperCase()}]
Style Instructions:
${styleGuide}

Translate, polish, and extract deep intelligence from the raw transmission according to the trans-coder style, returning a highly polished, immersive structured response.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3.5-flash',
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            id: { type: Type.STRING },
            title: { type: Type.STRING },
            polishedStory: { 
              type: Type.STRING, 
              description: "A highly immersive, stylized 3-4 sentence narrative rewriting the raw transmission in the specific theme of the chosen decrypter." 
            },
            dangerRating: { 
              type: Type.INTEGER, 
              description: "The assessed threat or danger level, from 1 (minimal) to 10 (extinction level catastrophe)." 
            },
            intelSummary: { 
              type: Type.STRING, 
              description: "A critical intelligence assessment summary of the core classified secret exposed by this document." 
            },
            keyConcepts: {
              type: Type.ARRAY,
              description: "Extracted elements representing factions, technologies, anomalies, or locations mentioned in this file.",
              items: {
                type: Type.OBJECT,
                properties: {
                  term: { type: Type.STRING, description: "A highly distinctive 1-3 word name for the term." },
                  definition: { type: Type.STRING, description: "A detailed 1-sentence definition of this term matching the style guide." },
                  type: { type: Type.STRING, description: "Category of concept: must be 'faction', 'location', 'technology', or 'omega-anomaly'." }
                },
                required: ["term", "definition", "type"]
              }
            },
            leads: {
              type: Type.ARRAY,
              description: "Suggested investigations or tactile game tips based on this information (2-3 items).",
              items: { type: Type.STRING }
            },
            recommendedProtocols: {
              type: Type.ARRAY,
              description: "A series of 2-3 precise mechanical or technical procedures matching the style tone (e.g. AMBER_REFILTER, OCC_LANTERN_SHUN, CORE_ANCHOR_MAX).",
              items: { type: Type.STRING }
            },
            diagramTitle: {
              type: Type.STRING,
              description: "A high-tech schematic or technical diagram title for this anomaly, e.g., 'CORE_VALVE_SLAG_MATRIX' or 'SHIBUYA_LANTERN_COORD'."
            },
            diagramType: {
              type: Type.STRING,
              description: "The design layout theme matching the decoder. Must be strictly one of: 'blueprint', 'nodes', or 'orbit'."
            },
            visualDescription: {
              type: Type.STRING,
              description: "A detailed 1-2 sentence description explaining what the schematic layout represents visually (structures, flows, signals)."
            },
            imagePrompt: {
              type: Type.STRING,
              description: "A descriptive text-to-image prompt (15-25 words) suitable for rendering/representing this anomaly graphically. Avoid words like 'gorgeous', 'photo' - specify retro high-tech engineering detail."
            },
            schematicPoints: {
              type: Type.ARRAY,
              description: "A list of 2-3 critical hotspots/sensor coordinates on the diagram. Specify exact percentage coordinate offsets.",
              items: {
                type: Type.OBJECT,
                properties: {
                  label: { type: Type.STRING, description: "A highly distinct 1-3 word identifier label (e.g., Vent Terminal B)." },
                  x: { type: Type.INTEGER, description: "Percentage position along X-axis (10 to 90)." },
                  y: { type: Type.INTEGER, description: "Percentage position along Y-axis (10 to 90)." },
                  detail: { type: Type.STRING, description: "A brief technical status or intelligence observation for this hotspot." }
                },
                required: ["label", "x", "y", "detail"]
              }
            }
          },
          required: [
            "id", 
            "title", 
            "polishedStory", 
            "dangerRating", 
            "intelSummary", 
            "keyConcepts", 
            "leads", 
            "recommendedProtocols",
            "diagramTitle",
            "diagramType",
            "visualDescription",
            "imagePrompt",
            "schematicPoints"
          ]
        }
      }
    });

    const text = response.text;
    if (!text) throw new Error("No decryption output was generated by the core.");

    const cleanText = text.replace(/```json/g, '').replace(/```/g, '').trim();
    const result = JSON.parse(cleanText) as FormattedLoreResult;
    // Ensure ID carries over correctly
    result.id = entry.id;
    return result;

  } catch (error) {
    console.error("Lore Decryption Error:", error);
    throw error;
  }
};